language: python

python:
  - 3.7

# workaround for 3.7 not available in default configuration
# travis-ci/travis-ci#9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

services:
  - postgresql

env:
  - DJANGO=2.0.8

script:
  - pytest
